# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio1
  template:
    metadata:
      labels:
        app: minio1
    spec:
      containers:
        - name: minio1
          image: markusstuppnig/minio:3.12
          command: []
          args: [] # Add any arguments here
